### ISSUE TITLE
Lấy yêu cầu khách hàng

### ISSUE THREAD

**Issue by giakhangnguyenlam** [giakhangnguyenlam/WebsiteTangQua#1]
Gặp khách hàng và lấy về các yêu cầu của khách hàng.

**Comment by giakhangnguyenlam** [comment]
- Chức năng đăng nhập và đăng ký.
- Tìm kiếm vật phẩm cần tặng.
- Giỏ hàng.
- Theo dõi tiến độ đơn hàng và nhận hình ảnh quà tặng trước khi giao.
- Đánh giá đơn hàng (review, chọn sao, ..).
- Gợi ý các phần quà tùy vào sự kiện như đám cưới, sinh nhật, noel, tết, …
- Thống kê của admin.
- Quản lí hệ thống nhân viên giao hàng.
- Quản lý đơn hàng.
- Thêm - xóa các mặt hàng và các dịch vụ quà tặng.
- Quản lý hệ thống xác nhận đơn hàng và thanh toán.
- Quản lý hệ thống giải quyết khiếu nại.

**Comment by duongdatnguyen** [comment]
Completed

**Comment by duongdatnguyen** [comment]
Done!!!!
