### ISSUE TITLE
Yêu cầu chức năng: Yêu cầu hệ thống

### ISSUE THREAD

**Issue by duongdatnguyen** [giakhangnguyenlam/WebsiteTangQua#2]
Phân tích yêu cầu của hệ thống của project <Các chức năng của website quà tặng>

**Comment by dinhphu28** [comment]
1. Hệ thống users gồm:
- Quản trị hệ thống
- Người dùng cuối
- Thủ kho
- Quản trị dịch vụ

**Comment by duongdatnguyen** [comment]
Done!!!
