### ISSUE TITLE
Yêu cầu chức năng: Yêu cầu người sử dụng

### ISSUE THREAD

**Issue by duongdatnguyen** [giakhangnguyenlam/WebsiteTangQua#3]
Phân tích yêu cầu của người sử dụng website quà tặng

**Comment by duongdatnguyen** [comment]
Các yêu cầu người sử dụng:
-Tạo ra các báo cáo về các đơn hàng mà người mua đã mua.
-Các bảng báo cáo về giá các loại quà tặng cũng như các chi phí phụ thêm
-Cung cấp các chức năng cho phép theo dõi đơn hàng đang được vận chuyển
-Cung cấp chức năng đánh giá sản phẩm, độ hài lòng vận chuyển

**Comment by dinhphu28** [comment]
Người dùng cuối:
+ Like sản phẩm và dịch vụ yêu thích
+ Thông tin cơ bản
+ Lưu các địa chỉ nhận hàng
+ Chọn ngày, giờ nhận hàng

**Comment by duongdatnguyen** [comment]
Done!!
