### ISSUE TITLE
Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by duongdatnguyen** [giakhangnguyenlam/WebsiteTangQua#4]
Phân tích yêu cầu phi chức năng của website quà tặng

**Comment by dinhphu28** [comment]
Các dịch vụ cộng thêm cho người dùng như:
+ Giao hàng đúng giờ, nhanh hay chậm
+ Cách thức giao hàng

**Comment by maihuong2505** [comment]
T bên lớp QLDAPM làm cùng đồ án á. Có gì add https://www.facebook.com/nu.lovely.2525/ cho dễ liên lạc.

**Comment by duongdatnguyen** [comment]
Done!!!
