### ISSUE TITLE
Lược đồ usecase cho toàn bộ website

### ISSUE THREAD

**Issue by giakhangnguyenlam** [giakhangnguyenlam/WebsiteTangQua#5]
Vẽ lược đồ usecase mô tả cho dự án.

**Comment by dinhphu28** [comment]
### Use-Case Diagram
- Design in draw.io
- Link of Diagram (*.drawio and *.svg files): [Use-Case Diagram](https://github.com/giakhangnguyenlam/WebsiteTangQua/tree/master/System_Design/UseCase)
- Open with [Draw.io - Diagrams.net](https://draw.io)

**Comment by duongdatnguyen** [comment]
Done
