### ISSUE TITLE
Đặc tả yêu cầu cho hệ thống quản lí

### ISSUE THREAD

**Issue by giakhangnguyenlam** [giakhangnguyenlam/WebsiteTangQua#6]
Sử dụng ngôn ngữ có cấu trúc để viết đặc tả yêu cầu cho hệ thống quản lí

**Comment by giakhangnguyenlam** [comment]
[https://github.com/giakhangnguyenlam/WebsiteTangQua/blob/master/DacTaHeThongQuanLi.docx](url)

**Comment by giakhangnguyenlam** [comment]
link dự phòng [https://drive.google.com/file/d/1ZxW5n6tiRxqPP3ofDzoom8xLML8VjJhi/view?usp=sharing](url)

**Comment by duongdatnguyen** [comment]
Done!!
