### ISSUE TITLE
Requirement Document

### ISSUE THREAD

**Issue by giakhangnguyenlam** [giakhangnguyenlam/WebsiteTangQua#8]
Viết mô tả yêu cầu tài liệu

**Comment by giakhangnguyenlam** [comment]
requirement document part 1:  [https://drive.google.com/file/d/1Hph6j3Lz4kkS0Xtk7leS70xvCEwn4FJm/view?usp=sharing](url)

**Comment by duongdatnguyen** [comment]
https://github.com/giakhangnguyenlam/WebsiteTangQua/blob/master/RequirementDocument_version2.docx

**Comment by duongdatnguyen** [comment]
Done!!!
